trigger:
  - main

parameters:
  - name: Project
    type: string
    default: $(Project)
  - name: Environment
    type: string
    default: $(Environment)
  - name: MasterUserPassword
    type: string
    default: $(MasterUserPassword)
  - name: VPCBlock
    type: string
    default: $(VPCBlock) 
  - name: VPCBlockSub1
    type: string
    default: $(VPCBlockSub1) 
  - name: VPCBlockSub2
    type: string
    default: $(VPCBlockSub2) 
  - name: VPCBlockSub3
    type: string
    default: $(VPCBlockSub3)
  - name: VPCBlockSub4
    type: string
    default: $(VPCBlockSub4)

pool:
  vmImage: ubuntu-latest

variables:
  credentials: 'aws-azure'
  region: 'us-east-1'

steps:
  - checkout: self  
  - task: CloudFormationCreateOrUpdateStack@1
    inputs:
      awsCredentials: $(credentials)
      regionName: $(region)
      stackName: 'dev'
      templateSource: 'file'
      templateFile: '$(Build.Repository.LocalPath)/main.yml'
      parameters: 
        Project: ${{parameters.Project}} 
        Environment: ${{parameters.Environment}} 
        MasterUserPassword: ${{parameters.MasterUserPassword}}
        VPCBlock: ${{parameters.VPCBlock}} 
        VPCBlockSub1: ${{parameters.VPCBlockSub1}} 
        VPCBlockSub2: ${{parameters.VPCBlockSub2}} 
        VPCBlockSub3: ${{parameters.VPCBlockSub3}}
        VPCBlockSub4: ${{parameters.VPCBlockSub4}}

