trigger:
- main

parameters:
  - name: Project
    type: string
  - name: Environment
    type: string
  - name: MasterUserPassword
    type: string
  - name: VPCBlock
    type: string
  - name: VPCBlockSub1
    type: string
  - name: VPCBlockSub2
    type: string
  - name: VPCBlockSub3
    type: string
  - name: VPCBlockSub4
    type: string

pool:
  vmImage: ubuntu-latest

variables:
  credentials: 'aws-azure'
  region: 'us-east-1'

steps:
- checkout: self  

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: $(credentials)
    regionName: $(region)
    stackName: 'dev'
    templateSource: 'file'
    templateFile: '$(Build.Repository.LocalPath)/main.yml'
    parameters: 
      Project: ${{Project}} 
      Environment: ${{Environment}} 
      MasterUserPassword: ${{MasterUserPassword}}
      VPCBlock: ${{VPCBlock}} 
      VPCBlockSub1: ${{VPCBlockSub1}} 
      VPCBlockSub2: ${{VPCBlockSub2}} 
      VPCBlockSub3: ${{VPCBlockSub3}}
      VPCBlockSub4: ${{VPCBlockSub4}}
      
