trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  credentials: 'aws-azure'
  region: 'us-east-1'

steps:
- checkout: self  

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: $(credentials)
    regionName: $(region)
    stackName: 'dev'
    templateSource: 'file'
    templateFile: '$(Build.Repository.LocalPath)/main.yml'
    templateParameters: '-Project $(Project) -Environment $(Environment) -MasterUserPassword $(MasterUserPassword)
      -VPCBlock $(VPCBlock) -VPCBlockSub1 $(VPCBlockSub1) -VPCBlockSub2 $(VPCBlockSub2) -VPCBlockSub3 $(VPCBlockSub3)
      -VPCBlockSub4 $(VPCBlockSub4)'
      
