trigger:
- main

parameters:
  - name: Project
    type: string
    Default: $(Project)
  - name: Environment
    type: string
    Default: $(Environment)
  - name: MasterUserPassword
    type: string
    Default: $(MasterUserPassword)
  - name: VPCBlock
    type: string
    Default: $(VPCBlock) 
  - name: VPCBlockSub1
    type: string
    Default: $(VPCBlockSub1) 
  - name: VPCBlockSub2
    type: string
    Default: $(VPCBlockSub2) 
  - name: VPCBlockSub3
    type: string
    Default: $(VPCBlockSub3)
  - name: VPCBlockSub4
    type: string
    Default: $(VPCBlockSub4)

pool:
  vmImage: ubuntu-latest

variables:
  credentials: 'aws-azure'
  region: 'us-east-1'

steps:
- checkout: self  

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: $(credentials)
    regionName: $(region)
    stackName: 'dev'
    templateSource: 'file'
    templateFile: '$(Build.Repository.LocalPath)/main.yml'
    parameters: 
      Project: $(Project) 
      Environment: $(Environment) 
      MasterUserPassword: $(MasterUserPassword)
      VPCBlock: $(VPCBlock) 
      VPCBlockSub1: $(VPCBlockSub1) 
      VPCBlockSub2: $(VPCBlockSub2) 
      VPCBlockSub3: $(VPCBlockSub3)
      VPCBlockSub4: $(VPCBlockSub4)
      
