AWSTemplateFormatVersion: '2010-09-09'
Description: ''

Parameters:
  Project:
    Description: The project that this cluster is use for
    Type: String

  Environment:
    Description: The environment (e.g., dev, prod)
    Type: String

  MasterUserPassword:
    Description: The master password for the DB instance.
    Type: String
    NoEcho: true

  MasterUser:
    Description: The master user for the DB instance.
    Type: String
    NoEcho: true

  VPCBlock:
    Description: The CIDR block for the VPC.
    Type: String
    Default: '12.0.0.0/16'

  VPCBlockSub1:
    Description: The CIDR block for the VPC.
    Type: String
    Default: '12.0.1.0/24'

  VPCBlockSub2:
    Description: The CIDR block for the VPC.
    Type: String
    Default: '12.0.2.0/24'

  VPCBlockSub3:
    Description: The CIDR block for the VPC.
    Type: String
    Default: '12.0.3.0/24'

  VPCBlockSub4:
    Description: The CIDR block for the VPC.
    Type: String
    Default: '12.0.4.0/24'


Resources:

  #----------------------------------------- network -------------------------------

  EC2VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VPCBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: 'default'
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-main-${Environment}'

  EC2Subnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !GetAtt EC2Subnet2.AvailabilityZone
      CidrBlock: !Ref VPCBlockSub1
      VpcId: !Ref EC2VPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: !Sub 'kubernetes.io/cluster/${Project}-eks-cluster-${Environment}'
          Value: 'owned'
        - Key: 'kubernetes.io/role/elb'
          Value: '1'
        - Key: 'Name'
          Value: !Sub 'public-${EC2Subnet2.AvailabilityZone}'

  EC2Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Sub 'us-east-1b'
      CidrBlock: !Ref VPCBlockSub2
      VpcId: !Ref EC2VPC
      MapPublicIpOnLaunch: false
      Tags:
        - Key: !Sub 'kubernetes.io/cluster/${Project}-eks-cluster-${Environment}'
          Value: 'owned'
        - Key: 'kubernetes.io/role/internal-elb'
          Value: '1'
        - Key: 'Name'
          Value: !Sub 'private-us-east-1b'

  EC2Subnet3:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !GetAtt EC2Subnet4.AvailabilityZone
      CidrBlock: !Ref VPCBlockSub3
      VpcId: !Ref EC2VPC
      MapPublicIpOnLaunch: true
      Tags:
        - Key: !Sub 'kubernetes.io/cluster/${Project}-eks-cluster-${Environment}'
          Value: 'owned'
        - Key: 'kubernetes.io/role/elb'
          Value: '1'
        - Key: 'Name'
          Value: !Sub 'public-${EC2Subnet4.AvailabilityZone}'

  EC2Subnet4:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Sub 'us-east-1a'
      CidrBlock: !Ref VPCBlockSub4
      VpcId: !Ref EC2VPC
      MapPublicIpOnLaunch: false
      Tags:
        - Key: !Sub 'kubernetes.io/cluster/${Project}-eks-cluster-${Environment}'
          Value: 'owned'
        - Key: 'kubernetes.io/role/internal-elb'
          Value: '1'
        - Key: 'Name'
          Value: !Sub 'private-us-east-1a'

  EC2InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-igw-${Environment}'

  EC2VPCGatewayAttachment:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref EC2VPC
      InternetGatewayId: !Ref EC2InternetGateway

  EC2EIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: 'vpc'
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-nat-a-eip-${Environment}'

  EC2EIP2:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: 'vpc'
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-nat-b-eip-${Environment}'

  EC2NatGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      SubnetId: !Ref EC2Subnet3
      Tags:
        - Key: 'Name'
          Value:  !Sub '${Project}-nat-a-${Environment}'
      AllocationId: !GetAtt EC2EIP.AllocationId

  EC2NatGateway2:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      SubnetId: !Ref EC2Subnet
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-nat-b-${Environment}'
      AllocationId: !GetAtt EC2EIP2.AllocationId

  EC2RouteTable2:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref EC2VPC
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-public-rt-${Environment}'
  
  EC2SubnetRouteTableAssociation1:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref EC2Subnet
      RouteTableId: !Ref EC2RouteTable2
  
  EC2SubnetRouteTableAssociation2:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref EC2Subnet3
      RouteTableId: !Ref EC2RouteTable2

  EC2RouteTable4:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref EC2VPC
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-private-rt-a-${Environment}'

  EC2SubnetRouteTableAssociation3:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref EC2Subnet4
      RouteTableId: !Ref EC2RouteTable4

  EC2RouteTable5:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref EC2VPC
      Tags:
        - Key: 'Name'
          Value: !Sub '${Project}-private-rt-b-${Environment}'

  EC2SubnetRouteTableAssociation4:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref EC2Subnet2
      RouteTableId: !Ref EC2RouteTable5

  EC2Route:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref EC2InternetGateway
      RouteTableId: !Ref EC2RouteTable2

  EC2Route2:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref EC2NatGateway
      RouteTableId: !Ref EC2RouteTable4

  EC2Route3:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: '0.0.0.0/0'
      NatGatewayId: !Ref EC2NatGateway2
      RouteTableId: !Ref EC2RouteTable5

  #----------------------------------------- eks cluster -------------------------------

  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: '/'
      RoleName: !Sub '${Project}-eks-rol-${Environment}'
      AssumeRolePolicyDocument: '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"eks.amazonaws.com"},"Action":"sts:AssumeRole"}]}'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'

  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Sub '${Project}-eks-cluster-${Environment}'
      RoleArn: !GetAtt IAMRole.Arn
      Version: '1.23'
      ResourcesVpcConfig:
        SubnetIds:
          - !Ref EC2Subnet2
          - !Ref EC2Subnet3
          - !Ref EC2Subnet
          - !Ref EC2Subnet4
      KubernetesNetworkConfig:
        ServiceIpv4Cidr: '10.100.0.0/16'

  IAMRole2:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: '/'
      RoleName: !Sub '${Project}-eks-nodes-rol-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
          - Effect: 'Allow'
            Principal:
              Federated: 'arn:aws:iam::438555236323:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/${!Ref EKSCluster}'
            Action: 'sts:AssumeRoleWithWebIdentity'
      MaxSessionDuration: 3600
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy'
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly'
        - 'arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy'

  EC2SecurityGroup2:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.'
      GroupName: !Sub 'eks-cluster-sg-${Project}-eks-cluster-${Environment}'
      Tags:
        - Key: !Sub 'kubernetes.io/cluster/${Project}-eks-cluster-${Environment}'
          Value: 'owned'
        - Key: 'Name'
          Value: !Sub 'eks-cluster-sg-${Project}-eks-cluster-${Environment}'
      VpcId: !Ref EC2VPC
      SecurityGroupIngress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: '-1'
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: '-1'

  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      NodegroupName: !Sub '${Project}-private-nodes-${Environment}'
      ClusterName: !Ref EKSCluster
      Version: '1.23'
      ScalingConfig:
        MinSize: 1
        MaxSize: 10
        DesiredSize: 4
      InstanceTypes:
        - 't3.medium'
      Subnets:
        - !Ref EC2Subnet2
        - !Ref EC2Subnet4
      NodeRole: !GetAtt IAMRole2.Arn
      Labels:
        role: 'general'
      DiskSize: 20
      Tags: {}
      CapacityType: 'ON_DEMAND'
      RemoteAccess:
        Ec2SshKey: !Sub 'agricola_${Environment}'
        SourceSecurityGroups:
          - !Ref EC2SecurityGroup2

    


  # ----------------------------------------- node autoscaler -------------------------------

  IAMManagedPolicy2:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub '${Project}-autoscaler-pol-${Environment}'
      Path: '/'
      PolicyDocument: '{"Statement":[{"Action":["autoscaling:DescribeAutoScalingGroups","autoscaling:DescribeAutoScalingInstances","autoscaling:DescribeLaunchConfigurations","autoscaling:DescribeTags","autoscaling:SetDesiredCapacity","autoscaling:TerminateInstanceInAutoScalingGroup","ec2:DescribeLaunchTemplateVersions"],"Effect":"Allow","Resource":"*"}],"Version":"2012-10-17"}'

  # ----------------------------------------- alb controller -------------------------------

  # moved this rol to terraform since is use for kubernetes resources

  # ----------------------------------------- external dns ---------------------------------

  # moved this rol to terraform since is use for kubernetes resources

  # ----------------------------------------- rds ------------------------------------------

  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'rds sg'
      GroupName: !Sub '${Project}-rds-sg-${Environment}'
      VpcId: !Ref EC2VPC
      SecurityGroupIngress:
        - CidrIp: !Ref VPCBlock
          FromPort: 5432
          IpProtocol: 'tcp'
          ToPort: 5432
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          IpProtocol: '-1'

  RDSDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'utility cluster subnet group'
      DBSubnetGroupName: !Sub '${Project}-subnet-gr-${Environment}'
      SubnetIds:
        - !Ref EC2Subnet2
        - !Ref EC2Subnet4

  RDSDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Sub '${Project}-sonardb-${Environment}'
      AllocatedStorage: 20
      DBInstanceClass: 'db.t3.micro'
      Engine: 'postgres'
      MasterUsername: !Ref MasterUser
      MasterUserPassword: !Ref MasterUserPassword
      DBName: 'sonardb'
      PreferredBackupWindow: '21:00-23:00'
      BackupRetentionPeriod: 30
      AvailabilityZone: !GetAtt EC2Subnet3.AvailabilityZone
      PreferredMaintenanceWindow: 'sun:00:00-sun:03:00'
      MultiAZ: false
      EngineVersion: '14.6'
      AutoMinorVersionUpgrade: true
      LicenseModel: 'postgresql-license'
      PubliclyAccessible: false
      StorageType: 'gp2'
      Port: 5432
      CopyTagsToSnapshot: false
      MonitoringInterval: 0
      EnableIAMDatabaseAuthentication: false
      EnablePerformanceInsights: false
      DeletionProtection: false
      DBSubnetGroupName: !Sub '${Project}-subnet-gr-${Environment}'
      VPCSecurityGroups:
        - !Ref EC2SecurityGroup
      DBParameterGroupName: 'default.postgres14'
      OptionGroupName: 'default:postgres-14'
      CACertificateIdentifier: 'rds-ca-rsa2048-g1'



  

